export const defaultWordList = [
  'a', 'an', 'at', 'as', 'and', 'are',
  'be', 'by',
  'do',
  'eat', 'end',
  'for', 'from',
  'get', 'go',
  'have', 'he', 'her', 'his',
  'in', 'is', 'it',
  'let',
  'me', 'my',
  'no', 'not',
  'of', 'on', 'or', 'our',
  'put',
  'run',
  'say', 'see', 'she', 'so',
  'the', 'they', 'to',
  'up', 'us', 'use',
  'we', 'who', 'with',
  'you', 'your',
  'about', 'after',
  'back', 'been', 'before',
  'call', 'can', 'come', 'could',
  'down',
  'find', 'first',
  'give', 'good',
  'hand', 'has', 'here', 'how',
  'just',
  'know',
  'like', 'look',
  'make', 'many', 'more', 'most',
  'new', 'now',
  'only', 'other', 'over',
  'people',
  'right',
  'same', 'see', 'some',
  'take', 'than', 'that', 'their', 'them', 'then', 'there', 'these', 'think', 'time', 'two',
  'want', 'way', 'well', 'what', 'when', 'which', 'will', 'work', 'would',
  'year',
  'quick', 'brown', 'fox', 'jumps', 'over', 'lazy', 'dog',
  'pack', 'my', 'box', 'with', 'five', 'dozen', 'liquor', 'jugs',
  'how', 'vexingly', 'daft', 'zebras', 'jump',
  'waltz', 'nymph', 'for', 'jigs', 'vex', 'bud',
  'sphinx', 'of', 'black', 'quartz', 'judge', 'vow',
  'fix', 'problem', 'quickly', 'galvanized', 'jets'
]

// You can add more word lists here in the future