export const defaultWordList = [
  // 1-letter words
  'a', 'i',

  // 2-letter words
  'an', 'as', 'at', 'be', 'by', 'do', 'go', 'he', 'if', 'in', 'is', 'it', 'me', 'my', 'no', 'of', 'on', 'or', 'to', 'up', 'us', 'we',

  // 3-letter words
  'act', 'add', 'age', 'ago', 'aid', 'aim', 'air', 'all', 'and', 'any', 'are', 'arm', 'ask', 'bad', 'bag', 'bar', 'bed', 'big', 'bit', 'box', 'boy', 'bud', 'bus', 'but', 'buy', 'can', 'car', 'cat', 'cut', 'dad', 'day', 'did', 'die', 'dog', 'dry', 'due', 'ear', 'eat', 'egg', 'end', 'eye', 'far', 'fat', 'fee', 'few', 'fit', 'fix', 'fly', 'for', 'fox', 'fun', 'gap', 'gas', 'get', 'god', 'got', 'gun', 'had', 'has', 'hat', 'hay', 'hen', 'her', 'hey', 'him', 'hip', 'his', 'hit', 'hot', 'how', 'ice', 'ill', 'ink', 'inn', 'jam', 'jar', 'jet', 'job', 'joy', 'key', 'kid', 'kit', 'lab', 'lag', 'lap', 'law', 'lay', 'leg', 'let', 'lid', 'lie', 'lip', 'log', 'lot', 'low', 'mad', 'man', 'map', 'may', 'met', 'mix', 'mud', 'mug', 'nap', 'net', 'new', 'nod', 'not', 'now', 'nut', 'oak', 'odd', 'off', 'oil', 'old', 'one', 'our', 'out', 'own', 'pay', 'put', 'ran', 'red', 'run', 'sat', 'say', 'see', 'set', 'she', 'sir', 'sit', 'six', 'sky', 'son', 'sun', 'the', 'top', 'try', 'use', 'vex', 'vow', 'war', 'was', 'way', 'wet', 'who', 'why', 'you',

  // 4-letter words
  'able', 'also', 'area', 'arms', 'away', 'back', 'beat', 'been', 'best', 'bite', 'blue', 'book', 'both', 'call', 'calm', 'came', 'care', 'case', 'cell', 'city', 'cold', 'come', 'cool', 'cope', 'dark', 'data', 'deal', 'desk', 'died', 'door', 'down', 'draw', 'drop', 'drove', 'easy', 'edge', 'else', 'even', 'ever', 'eyes', 'face', 'fact', 'fall', 'fear', 'feel', 'feet', 'fell', 'felt', 'fill', 'find', 'fine', 'fire', 'five', 'form', 'four', 'free', 'from', 'full', 'game', 'gave', 'gaze', 'gets', 'girl', 'give', 'glad', 'goes', 'gone', 'good', 'grew', 'grin', 'hair', 'half', 'hand', 'hard', 'hate', 'have', 'head', 'hear', 'held', 'help', 'here', 'hers', 'high', 'hill', 'hold', 'home', 'hope', 'huge', 'hung', 'hurt', 'idea', 'into', 'iron', 'it\'s', 'jeans', 'just', 'keep', 'kept', 'kids', 'kind', 'knew', 'know', 'lady', 'land', 'last', 'late', 'lead', 'left', 'less', 'life', 'like', 'line', 'lips', 'live', 'long', 'look', 'lose', 'loss', 'lost', 'love', 'made', 'make', 'many', 'mean', 'meet', 'mind', 'miss', 'more', 'most', 'move', 'much', 'must', 'name', 'near', 'need', 'next', 'nice', 'nose', 'note', 'okay', 'once', 'only', 'onto', 'open', 'over', 'pack', 'pain', 'pair', 'pare', 'part', 'pass', 'past', 'pick', 'plan', 'play', 'pull', 'pure', 'push', 'quit', 'quite', 'read', 'real', 'rest', 'ring', 'rise', 'road', 'rock', 'room', 'rose', 'safe', 'said', 'same', 'save', 'says', 'seat', 'seem', 'seen', 'self', 'send', 'sent', 'ship', 'shop', 'show', 'shut', 'side', 'sigh', 'sign', 'sing', 'sink', 'site', 'size', 'skin', 'slip', 'slow', 'soft', 'some', 'soon', 'sort', 'soul', 'spot', 'star', 'stay', 'step', 'stop', 'such', 'sure', 'take', 'talk', 'tall', 'tell', 'than', 'that', 'them', 'then', 'they', 'thin', 'this', 'those', 'time', 'tiny', 'told', 'tone', 'took', 'town', 'tree', 'true', 'turn', 'type', 'used', 'very', 'view', 'wait', 'walk', 'wall', 'want', 'warm', 'wash', 'wear', 'week', 'well', 'went', 'were', 'what', 'when', 'wide', 'wife', 'will', 'wind', 'wish', 'with', 'wolf', 'word', 'work', 'year', 'your', 'zeal',

  // 5-letter words
  'about', 'above', 'after', 'again', 'ahead', 'alive', 'alone', 'along', 'angry', 'apart', 'asked', 'began', 'black', 'blood', 'brain', 'break', 'brave', 'breath', 'bring', 'broke', 'brown', 'build', 'built', 'catch', 'cause', 'chair', 'chance', 'change', 'check', 'chest', 'child', 'class', 'clear', 'close', 'could', 'cover', 'crazy', 'cross', 'crowd', 'death', 'doubt', 'dream', 'dress', 'drink', 'drive', 'early', 'empty', 'enjoy', 'enter', 'every', 'exact', 'eyes', 'face', 'fall', 'fast', 'felt', 'field', 'fight', 'final', 'first', 'focus', 'force', 'found', 'friend', 'front', 'funny', 'given', 'glass', 'going', 'grace', 'green', 'ground', 'group', 'guard', 'guess', 'hair', 'hands', 'happy', 'heard', 'heart', 'heavy', 'hello', 'hope', 'horse', 'house', 'human', 'inside', 'jeans', 'judge', 'jumps', 'kept', 'knife', 'known', 'large', 'laugh', 'learn', 'leave', 'left', 'let\'s', 'light', 'liked', 'little', 'lived', 'looks', 'loved', 'magic', 'maybe', 'meant', 'metal', 'might', 'mind', 'money', 'month', 'mouth', 'moved', 'music', 'needs', 'never', 'night', 'noise', 'north', 'nose', 'notice', 'often', 'okay', 'older', 'once', 'opened', 'other', 'own', 'pain', 'paper', 'party', 'passed', 'peace', 'phone', 'piece', 'place', 'plan', 'point', 'power', 'press', 'pulled', 'pushed', 'quick', 'quiet', 'quite', 'reach', 'ready', 'right', 'river', 'rolled', 'room', 'round', 'running', 'said', 'same', 'scared', 'second', 'seemed', 'seen', 'sense', 'serve', 'seven', 'shake', 'share', 'sharp', 'short', 'shot', 'should', 'show', 'side', 'sight', 'simple', 'since', 'skill', 'sleep', 'slowly', 'small', 'smile', 'snow', 'soft', 'solve', 'some', 'sorry', 'sound', 'south', 'space', 'speak', 'spent', 'spoke', 'spread', 'stand', 'start', 'state', 'stayed', 'steps', 'still', 'stood', 'stop', 'story', 'street', 'strong', 'stuck', 'sure', 'table', 'taken', 'teeth', 'thank', 'their', 'there', 'these', 'thing', 'think', 'third', 'those', 'three', 'threw', 'through', 'tight', 'times', 'tired', 'today', 'told', 'took', 'touch', 'toward', 'town', 'train', 'tried', 'truck', 'truly', 'trust', 'truth', 'turned', 'twice', 'under', 'until', 'using', 'usual', 'voice', 'wait', 'walked', 'want', 'warm', 'watch', 'water', 'weeks', 'where', 'which', 'while', 'white', 'whole', 'whose', 'woman', 'women', 'words', 'work', 'world', 'worry', 'worse', 'would', 'write', 'wrong', 'years', 'young', 'your',

  // 6-letter words
  'action', 'adapt', 'afraid', 'agreed', 'almost', 'always', 'answer', 'anyone', 'anyway', 'around', 'asking', 'attack', 'became', 'become', 'before', 'behind', 'better', 'beyond', 'bottom', 'breath', 'bridge', 'bright', 'broken', 'called', 'cannot', 'change', 'choice', 'choose', 'coming', 'common', 'corner', 'could', 'course', 'create', 'crying', 'during', 'easily', 'energy', 'enough', 'entire', 'exactly', 'except', 'expect', 'explain', 'family', 'father', 'feeling', 'filled', 'finger', 'finish', 'follow', 'forget', 'forward', 'friend', 'future', 'giving', 'ground', 'growth', 'happen', 'health', 'heard', 'herself', 'honest', 'impact', 'inside', 'instead', 'jumped', 'keeping', 'killed', 'kissed', 'knew', 'knowing', 'laughed', 'laughing', 'leaned', 'learned', 'lifted', 'listen', 'little', 'living', 'looked', 'making', 'matter', 'maybe', 'memory', 'middle', 'minute', 'moment', 'months', 'mother', 'moving', 'myself', 'nature', 'needed', 'never', 'nodded', 'notice', 'office', 'opened', 'other', 'people', 'person', 'picked', 'placed', 'pocket', 'pulled', 'pushed', 'raised', 'rather', 'reached', 'really', 'reason', 'remain', 'remember', 'replied', 'return', 'rolled', 'saying', 'school', 'second', 'seemed', 'should', 'showed', 'sighed', 'silent', 'simply', 'single', 'sister', 'slowly', 'smiled', 'softly', 'sounds', 'spirit', 'spread', 'stared', 'started', 'stayed', 'stepped', 'still', 'stood', 'street', 'strong', 'sudden', 'taking', 'talked', 'though', 'thought', 'throat', 'through', 'told', 'toward', 'trying', 'turned', 'twenty', 'understand', 'waited', 'walked', 'wanted', 'watched', 'waved', 'weight', 'window', 'within', 'without', 'wonder', 'worked', 'world', 'would', 'yelled',

  // 7+ letter words
  'ability', 'achieve', 'acquire', 'actually', 'adventure', 'afternoon', 'algorithm', 'already', 'although', 'anything', 'apartment', 'appeared', 'attention', 'balance', 'bathroom', 'beautiful', 'bedroom', 'believe', 'beneath', 'benefit', 'between', 'brilliant', 'building', 'business', 'carefully', 'challenge', 'changed', 'character', 'children', 'clearly', 'collaborate', 'communicate', 'completely', 'continued', 'control', 'conversation', 'courage', 'covered', 'culture', 'curious', 'dangerous', 'darkness', 'daughter', 'decision', 'definitely', 'develop', 'different', 'discover', 'distance', 'education', 'efficient', 'empathy', 'enhance', 'environment', 'everyone', 'everything', 'exactly', 'experience', 'explained', 'expression', 'familiar', 'finally', 'fingers', 'followed', 'forehead', 'forever', 'forward', 'freedom', 'further', 'generate', 'getting', 'glanced', 'grinned', 'happened', 'harmony', 'himself', 'holding', 'however', 'hundred', 'husband', 'imagine', 'immediately', 'important', 'improve', 'information', 'innovate', 'integrity', 'kindness', 'kitchen', 'knowledge', 'leaving', 'letting', 'looking', 'managed', 'meeting', 'minutes', 'morning', 'motivate', 'muttered', 'myself', 'needed', 'nothing', 'noticed', 'obviously', 'offered', 'opening', 'opportunity', 'outside', 'passion', 'patience', 'perfect', 'perhaps', 'persevere', 'picture', 'pointed', 'positive', 'possible', 'potential', 'pressed', 'probably', 'problem',

  // Challenging words
  'abstruse', 'acquiesce', 'ameliorate', 'benevolent', 'cacophony', 'deleterious', 'ephemeral', 'facetious', 'garrulous', 'heterogeneous', 'idiosyncrasy', 'juxtapose', 'kaleidoscope', 'loquacious', 'mellifluous', 'nefarious', 'obfuscate', 'paradigm', 'quintessential', 'recalcitrant', 'surreptitious', 'tautology', 'ubiquitous', 'verisimilitude', 'wunderkind', 'xenophobia', 'yeoman', 'zeitgeist',

  // Pangrams (sentences using every letter of the alphabet)
  'the quick brown fox jumps over the lazy dog',
  'pack my box with five dozen liquor jugs',
  'how vexingly quick daft zebras jump',
  'sphinx of black quartz judge my vow',
  'fix problem quickly with galvanized jets'
]